/**
 * C3 ID Generator Interface & Implementation
 * Cryptographically strong ID generation abstraction.
 */

import { randomUUID } from 'crypto';

export interface IdGenerator {
  generate(prefix?: string): string;
  validate(id: string, prefix?: string): boolean;
}

export class CryptoIdGenerator implements IdGenerator {
  /**
   * Generates a cryptographically strong UUID v4, optionally prefixed (e.g., 'usr_550e8400-e29b-41d4-a716-446655440000').
   */
  generate(prefix?: string): string {
    const uuid = randomUUID();
    if (prefix) {
      const cleanPrefix = prefix.endsWith('_') ? prefix : `${prefix}_`;
      return `${cleanPrefix}${uuid}`;
    }
    return uuid;
  }

  /**
   * Validates if a string is a valid ID generated by this generator.
   */
  validate(id: string, prefix?: string): boolean {
    if (typeof id !== 'string' || id.trim() === '') {
      return false;
    }

    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

    if (!prefix) {
      return uuidRegex.test(id);
    }

    const cleanPrefix = prefix.endsWith('_') ? prefix : `${prefix}_`;
    if (!id.startsWith(cleanPrefix)) {
      return false;
    }

    const uuidPart = id.slice(cleanPrefix.length);
    return uuidRegex.test(uuidPart);
  }
}
